server:
  port: 8089
spring:
#  # MongoDB的配置
#  data:
#    mongodb:
#      host: 10.100.10.21
#      port: 27017
#      username: mtload
#      password: mtload
#      database: mtload
  # ----------------------------------------------------------------------
  # 配置 redis
  redis:
    lettuce:
      pool:
        max-total: 50
        min-idle: 1
        max-wait-millis: 5000
        max-idle: 8
        test-on-borrow: true
        test-on-return: true
        test-while-idle: true
    # 主应用redis，包含仓上PLC的点
    redis-master:
      port: 6379
      timeout: 5000
      database: 0
      hostName: 127.0.0.1
#      password: xbd%mtload123
    # 装车站应用redis，包含仓下PLC的点，雷达，光幕
    redis-slave:
      port: 6379
      timeout: 5000
      database: 0
      hostName: 127.0.0.1
#      password: xbd%mtload123
    # 装车站定位专用redis，可以和装车站应用redis相同
    redis-position:
      port: 6379
      timeout: 5000
      database: 0
#      password: xbd%mtload123
      hostName: 127.0.0.1
    # 云商接口专用redis
    redis-api:
      port: 6379
      timeout: 5000
      database: 0
      hostName: 127.0.0.1