server:
  port: 8089
spring:
#  # MongoDB的配置
#  data:
#    mongodb:
#      host: 10.100.10.21
#      port: 27017
#      username: mtload
#      password: mtload
#      database: mtload
  # ----------------------------------------------------------------------
  # 配置 redis
  redis:
    lettuce:
      pool:
        max-total: 50
        min-idle: 1
        max-wait-millis: 5000
        max-idle: 8
        test-on-borrow: true
        test-on-return: true
        test-while-idle: true
    # 主应用redis，包含仓上PLC的点
    redis-master:
      port: 6379
      timeout: 5000
      database: 0
      hostName: 127.0.0.1
#      password: xbd%mtload123
    # 装车站应用redis，包含仓下PLC的点，雷达，光幕
    redis-slave:
      port: 6379
      timeout: 5000
      database: 0
      hostName: 127.0.0.1
#      password: xbd%mtload123
    # 装车站定位专用redis，可以和装车站应用redis相同
    redis-position:
      port: 6379
      timeout: 5000
      database: 0
#      password: xbd%mtload123
      hostName: 127.0.0.1
    # 云商接口专用redis
    redis-api:
      port: 6379
      timeout: 5000
      database: 0
      hostName: 127.0.0.1
#spring:
#  datasource:
#    dynamic:
#      primary: mysql
#      datasource:
#        mysql:  #db1
#          url: jdbc:mysql://10.100.10.22:3306/mtload-task-master?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
#          driverClassName: com.mysql.cj.jdbc.Driver
#          username: root
#          password: mtload
##        oracle: #db2
##          url: jdbc:oracle:thin:@10.20.41.9:1521/tldb
##          driverClassName: oracle.jdbc.OracleDriver
##          username: tjhyzp
##          password: tjhyzp
#        oracle:  #db1
#          url: jdbc:mysql://10.100.10.22:3306/mtload-task-master?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false
#          driverClassName: com.mysql.cj.jdbc.Driver
#          username: root
#          password: mtload
#        sqlserver: #配置数据源2,此处配置的是sqlserver数据库
#          url: jdbc:sqlserver://192.168.5.148:1433;databasename=测试
#          username: sa
#          password: Mt@123456
#          driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#      type: com.alibaba.druid.pool.DruidDataSource
#      druid:
#        initial-size: 10
#        max-active: 100
#        min-idle: 10
#        max-wait: 60000
#        pool-prepared-statements: true
#        max-pool-prepared-statement-per-connection-size: 20
#        time-between-eviction-runs-millis: 60000
#        min-evictable-idle-time-millis: 300000
#        #Oracle need open
#        test-while-idle: true
#        test-on-borrow: false
#        test-on-return: false
#        stat-view-servlet:
#          enabled: true
#          url-pattern: /druid/*
#          #login-username: admin
#          #login-password: admin
#        filter:
#          stat:
#            log-slow-sql: true
#            slow-sql-millis: 1000
#            merge-sql: false
#          wall:
#            config:
#              multi-statement-allow: true
#  jackson:
#    date-format: yyyy-MM-dd HH:mm:ss
#    time-zone: GMT+8
#  profiles:
#    include: dev
#
#  # 配置 redis
#  redis:
#    lettuce:
#      pool:
#        max-total: 50
#        min-idle: 1
#        max-wait-millis: 5000
#        max-idle: 8
#        test-on-borrow: true
#        test-on-return: true
#        test-while-idle: true
#    port: 6380
#    password: xbd%mtload123
#    timeout: 5000
#    database: 0
#    host: 10.100.10.22
#test_flag: 0
#use_flag: hyc
#load_line: 400012
#cyz: datang2
#use_single_pre: false
#use_buffer_bunker_varied: true
#gross_weight_size: 12
#mybatis-plus:
#
#  configuration:
#    default-statement-timeout: 20
#
#  global-config:
#    db-config:
#      logic-delete-value: 1
#      logic-not-delete-value: 0
#tls:
#  pre:
#    mysql-url: jdbc:mysql://10.100.10.22:3306/mtload?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
#    mysql-username: root
#    mysql-password: mtload
#    pre-enable-log: true
#tls_task_url: http://10.100.10.22:8767/zcserver/taskfoo/api/taskactive/v1/syncAdminTask